In [3]:
import pandas as pd
import numpy as np
IntrusionData = pd.read_csv('data.csv',sep=',',index_col = False)
#IntrusionData.head()

In [ ]:
IntrusionData.shape

In [4]:
Xmatrix = IntrusionData.values
LabelVector = Xmatrix[:,-1]
Xmatrix = Xmatrix[:,:-1]

In [5]:
meanVector = np.mean(Xmatrix,axis = 0)

In [6]:
CenteredXmatrix = Xmatrix - meanVector

In [7]:
SdVector = np.std(CenteredXmatrix.astype(float),axis = 0)

In [8]:
CenteredXmatrix /= SdVector

In [ ]:
#CenteredXmatrix

In [9]:
covOfCenteredXmatrix = np.array([(CenteredXmatrix[0,:].astype(float))]).T@ np.array([(CenteredXmatrix[0,:].astype(float))])
for i in range(1,len(CenteredXmatrix)):
    covOfCenteredXmatrix +=   np.array([(CenteredXmatrix[i,:].astype(float))]).T@ np.array([(CenteredXmatrix[i,:].astype(float))])
covOfCenteredXmatrix /= len(CenteredXmatrix)

In [ ]:
#covOfCenteredXmatrix

In [ ]:
#covOfCenteredXmatrix1 = np.cov(CenteredXmatrix.astype(float).T)#, rowvar=False)

In [ ]:
#covOfCenteredXmatrix1

In [ ]:
#covOfCenteredXmatrix

In [ ]:
#covOfCenteredXmatrix.shape

In [10]:
eigenValues, eigenVectors = np.linalg.eig(covOfCenteredXmatrix)

In [ ]:
#eigenVectors

In [11]:
#listOfeigenValuesAndVectors = zip( eigenValues, eigenVectors )
#sorder
#listOfeigenValuesAndVectors.sort(key=lambda tup:tup[0], reverse=True)
#eigenValues,eigenVectors = zip(*listOfeigenValuesAndVectors)
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

In [11]:
eigenValues

array([6.74137034e+00, 4.85001779e+00, 2.18498292e+00, 1.88897298e+00,
       1.47821054e+00, 1.34408506e+00, 1.13799127e+00, 9.40905773e-01,
       1.02874312e+00, 1.01504409e+00, 9.96060830e-01, 1.00015583e+00,
       7.91113360e-01, 7.20721604e-01, 6.50773088e-01, 5.00651035e-01,
       4.49469213e-01, 4.06951850e-01, 3.47989784e-01, 2.12196666e-01,
       9.89803468e-02, 6.67643796e-02, 5.12510536e-02, 3.98871811e-02,
       7.17155903e-04, 4.14371681e-03, 9.08736088e-03, 1.63128175e-02,
       2.64488437e-02])

In [12]:
neededEigenVectors = []
for idx, val in enumerate(eigenValues):
    if (sum(eigenValues[0:idx])/sum(eigenValues))>0.9:
        neededEigenVectors = eigenVectors[:,0:idx]
        break

In [12]:
(sum(eigenValues[0:14])/sum(eigenValues))

0.9006336381577709

In [72]:
neededEigenVectors

array([[ 3.13869088e-05, -2.25722343e-05],
       [-4.55702872e-09, -1.47382897e-08],
       [ 9.99999965e-01,  2.63142244e-04],
       [ 2.63141536e-04, -9.99999965e-01],
       [ 1.07998805e-10,  1.83944862e-10],
       [-1.60419764e-12, -5.67045241e-12],
       [-3.48119748e-10, -7.33900801e-09],
       [-3.87517865e-10, -7.45890333e-09],
       [-1.47365550e-11, -1.06678188e-11],
       [-5.23715306e-12, -8.39205890e-12],
       [-1.00511209e-07,  1.00832866e-07],
       [-3.45550195e-08,  3.16704059e-08],
       [-2.45568775e-10,  3.39473649e-10],
       [-2.61857539e-10,  3.37565295e-10],
       [ 7.52390586e-10, -8.90171707e-10],
       [ 7.70610260e-10, -8.89045547e-10],
       [ 2.92020448e-10, -4.13929099e-10],
       [-1.32790056e-11,  7.63441953e-11],
       [-1.15451993e-10,  1.08119478e-10],
       [-9.78558461e-08, -6.24171219e-08],
       [-1.29389777e-07,  1.16202912e-07],
       [-5.02661289e-10,  4.93575918e-10],
       [ 2.90326485e-11, -5.18247514e-10],
       [ 2.

In [13]:
reconstructedXmatrix = CenteredXmatrix.astype(float)@neededEigenVectors
print(Xmatrix.shape)#neededEigenVectors.T.shape
print(neededEigenVectors.shape)
print(reconstructedXmatrix.shape)

(125973, 29)
(29, 14)
(125973, 14)


In [14]:
reconstructedXmatrix.shape
LabelVector
newData = np.insert(reconstructedXmatrix.astype(str), 2, values=LabelVector, axis=1) 
newData.shape

(125973, 15)

In [43]:
reconstructedXmatrix -= np.mean(reconstructedXmatrix,axis = 0)
reconstructedXmatrix /= np.std(reconstructedXmatrix.astype(float),axis = 0)
np.unique(LabelVector)
np.max(reconstructedXmatrix,axis = 0)

array([2.23185839e+02, 1.91780446e+02, 2.03018998e+02, 2.07809658e+02,
       9.84362328e-03, 2.15189811e+02, 2.22145534e+02, 2.16178110e+02,
       2.26535246e+02, 2.68581814e+02, 8.24794425e-03, 1.42808869e-02,
       2.14946437e+02, 1.85302284e+00])

# part2 kmeans

In [ ]:
#initializing k = 5 means 
k = 5
meanVector = {}
import random
RandomIndices = random.sample(range(0,len(reconstructedXmatrix)), 5)
print(RandomIndices)
for i in range(0,k):
    #meanVector[i] = 
    meanVector[i] = reconstructedXmatrix[RandomIndices[i],:]
#for index,value in enumerate(np.unique(LabelVector)):
#    meanVector[value] = reconstrucedXmatrix[index,:]
#meanVector
#RandomIndices

In [112]:
def getDistance(row1,row2):
    row1 = np.array(row1)
    row2 = np.array(row2)
    #print(row1)
    #print(row2)
    #print((np.sum((np.abs(row1-row2))**2))**(1/2))
    return (np.sum((np.abs(row1-row2))**2))**(1/2)
def getNearestClusterDistance(givenSample,meanVector1):
    distancesFromAllMeans = {}
    #print(len(meanVector1))
    for i in meanVector1:
        distancesFromAllMeans[i] = getDistance(givenSample,meanVector1[i])
    nearestMeanLabel = min(distancesFromAllMeans.items(), key=operator.itemgetter(1))[0]
    nearestMeanDistance = min(distancesFromAllMeans.values()); 
    #nearestMeanLabel = 0
    #nearestMeanDistance = getDistance(givenSample,meanVector1[0])
    #for i in meanVector1: 
     #   tempDistance = getDistance(givenSample,meanVector1[i])
      #  if tempDistance < nearestMeanDistance:
       #     nearestMeanLabel = i
        #    nearestMeanDistance = tempDistance  
    return nearestMeanDistance

In [110]:
reconstructedXmatrix[65000,:]

array([ 276.1583659 , -601.92732322])

In [113]:
meanVector = {}
import random
import operator
RandomIndex1 = random.sample(range(0,len(reconstructedXmatrix)), 1)
RandomIndex1 =random.randint(0,len(reconstructedXmatrix))
remainingIndices = list(range(0,len(reconstructedXmatrix)))
RandomIndex1 = 120000
#remainingIndices.remove(RandomIndex1[0])
remainingIndices.remove(RandomIndex1)
#meanVector[0] = reconstructedXmatrix[RandomIndex1[0],:]
meanVector[0] = reconstructedXmatrix[RandomIndex1,:]

for k in range(1,5):
    distancesOfRemainingVerticesWithNearestMean = {}
    for i in remainingIndices:
        distancesOfRemainingVerticesWithNearestMean[i] = getNearestClusterDistance(reconstructedXmatrix[i,:],meanVector)
    #findMaxKeywithrespecttodistance
    nextVetexIndex = max(distancesOfRemainingVerticesWithNearestMean.items(), key=operator.itemgetter(1))[0]
    print(nextVetexIndex)
    max_value = max(distancesOfRemainingVerticesWithNearestMean.values()); 
    print(max_value)
    tempList = [key for key, value in distancesOfRemainingVerticesWithNearestMean.items() if value == max_value]
    print(tempList)
    #assign that key as a the next vertex
    meanVector[k] = reconstructedXmatrix[nextVetexIndex,:]
    #removethatvertexfromremainingIndices
    for i in tempList:
        remainingIndices.remove(i)
    #remainingIndices.remove(max(distancesOfRemainingVerticesWithNearestMean, key=distancesOfRemainingVerticesWithNearestMean.get))
    


125429
1379963666.4549322
[125429]
62233
1309934808.9144394
[62233]
60570
686588248.7938263
[60570]


KeyboardInterrupt: 

In [86]:
meanVector

{0: array([   156.12529341, -27077.95982729]),
 1: array([1.37996384e+09, 3.63125980e+05]),
 2: array([ 3.44699284e+05, -1.30993736e+09]),
 3: array([6.93375616e+08, 1.82456422e+05]),
 4: array([ 1.05334457e+05, -4.00291047e+08])}

In [ ]:
#len(reconstructedXmatrix)
len(remainingIndices)

In [ ]:
meanVector

In [87]:

def getNearestCluster(givenSample,meanVector1):
    #distancesFromAllMeans = {}
    nearestMeanLabel = 3
    nearestMeanDistance = getDistance(givenSample,meanVector1[3])
    #print(len(meanVector1))
    for i in meanVector1: 
        tempDistance = getDistance(givenSample,meanVector1[i])
        if  tempDistance < nearestMeanDistance:
            nearestMeanLabel = i
            nearestMeanDistance = tempDistance  
    return nearestMeanLabel

In [ ]:
#meanvertices = [109828, 7739, 21128, 2701, 61835]
#reconstructedXmatrix[i,:]
for i in meanVector:
    for j in meanVector:
        print("distance between "+str(i)+" and "+str(j)+" is ")
        print(getDistance(meanVector[i],meanVector[j]))
    

In [88]:
AssociatedClusterForEachPoint1 = []
for i in range(0,len(reconstructedXmatrix)):
    AssociatedClusterForEachPoint1.append(getNearestCluster(reconstructedXmatrix[i,:],meanVector))

In [89]:
len(AssociatedClusterForEachPoint1)

125973

In [90]:
len(reconstructedXmatrix)

125973

In [97]:
count = 0
for j,value in enumerate(AssociatedClusterForEachPoint1):    
            if value == 0:
                #numerVector += reconstructedXmatrix[j,:]
                #print(reconstructedXmatrix[j,:])
                count += 1
print(count)

125965


In [154]:
for i in meanVector:
        numerVector = np.array([0.0]*len(meanVector[0]))
        count = 0
        for j,value in enumerate(AssociatedClusterForEachPoint1):
            if value == i:
                numerVector += reconstructedXmatrix[j,:]
                #print(reconstructedXmatrix[j,:])
                count += 1
        if count!= 0:
            print("mean number is ")
            print(i)
            print('points associated are')
            print(count)
            meanVector[i] = (numerVector/count)
        else:
            print('no points associated to mean number')
            print(i)

IndexError: index 125973 is out of bounds for axis 0 with size 125973

In [98]:
iterationNumber = 0
while (iterationNumber<25):
#for i in range(0,10)
    iterationNumber += 1
    print("iteration is")
    print(iterationNumber)
    AssociatedClusterForEachPoint1 = []
    for i in range(0,len(reconstructedXmatrix)):
        AssociatedClusterForEachPoint1.append(getNearestCluster(reconstructedXmatrix[i,:],meanVector))
    for i in meanVector:
        numerVector = np.array([0.0]*len(meanVector[0]))
        count = 0
        for j,value in enumerate(AssociatedClusterForEachPoint1):
            if value == i:
                numerVector += reconstructedXmatrix[j,:]
                #print(reconstructedXmatrix[j,:])
                count += 1
        if count!= 0:
            print("mean number is ")
            print(i)
            print('points associated are')
            print(count)
            meanVector[i] = (numerVector/count)
        else:
            print('no points associated to mean number')
            print(i)
    #if np.array_equal(AssociatedClusterForEachPoint,AssociatedClusterForEachPoint1):
    #    break
    #else:
     #   AssociatedClusterForEachPoint = AssociatedClusterForEachPoint1
    print(meanVector)

    

iteration is
1
mean number is 
0
points associated are
125965
mean number is 
1
points associated are
2
mean number is 
2
points associated are
1
mean number is 
3
points associated are
3
mean number is 
4
points associated are
2
{0: array([11877.45719237, -3022.44261912]), 1: array([1.27374165e+09, 3.35174450e+05]), 2: array([ 3.44699284e+05, -1.30993736e+09]), 3: array([5.65551112e+08, 1.48819837e+05]), 4: array([ 1.05334457e+05, -4.00291047e+08])}
iteration is
2
mean number is 
0
points associated are
125965
mean number is 
1
points associated are
2
mean number is 
2
points associated are
1
mean number is 
3
points associated are
3
mean number is 
4
points associated are
2
{0: array([11877.45719237, -3022.44261912]), 1: array([1.27374165e+09, 3.35174450e+05]), 2: array([ 3.44699284e+05, -1.30993736e+09]), 3: array([5.65551112e+08, 1.48819837e+05]), 4: array([ 1.05334457e+05, -4.00291047e+08])}
iteration is
3
mean number is 
0
points associated are
125965
mean number is 
1
points ass

KeyboardInterrupt: 

In [ ]:
#AssociatedClusterForEachPoint
#meanVector

In [ ]:

#AssociatedClusterForEachPoint = [0]*len(reconstructedXmatrix)
AssociatedClusterForEachPoint = []
for i in range(0,len(reconstructedXmatrix)):
    AssociatedClusterForEachPoint.append(getNearestCluster(reconstructedXmatrix[i,:],meanVector))
for i in meanVector:
    numerVector = np.array([0.0]*len(meanVector[0]))
    count = 0
    for j,value in enumerate(AssociatedClusterForEachPoint):
        if j == i:
            numerVector += reconstructedXmatrix[value,:]
            count += 1
    if count != 0:
        meanVector[i] = numerVector/count

AssociatedClusterForEachPoint1 = []
for i in range(0,len(reconstructedXmatrix)):
    AssociatedClusterForEachPoint1.append(getNearestCluster(reconstructedXmatrix[i,:],meanVector))
    
#while !(np.array_equal(AssociatedClusterForEachPoint,AssociatedClusterForEachPoint1)):
iterationNumber = 0
while (1==1):
#for i in range(0,10)
    iterationNumber += 1
    print(iterationNumber)
    AssociatedClusterForEachPoint1 = []
    for i in range(0,len(reconstructedXmatrix)):
        AssociatedClusterForEachPoint1.append(getNearestCluster(reconstructedXmatrix[i,:],meanVector))
    for i in meanVector:
        numerVector = np.array([0.0]*len(meanVector[0]))
        count = 0
        for j,value in enumerate(AssociatedClusterForEachPoint1):
            if j == i:
                numerVector += reconstructedXmatrix[value,:]
                count += 1
        if count != 0:
            meanVector[i] = numerVector/count
    if np.array_equal(AssociatedClusterForEachPoint,AssociatedClusterForEachPoint1):
        break
    else:
        AssociatedClusterForEachPoint = AssociatedClusterForEachPoint1
        print(meanVector)

    

# part3

In [127]:
from sklearn import mixture
#clusterer = GaussianMixture(5, 'diag')
#clusterer.fit(reconstructedXmatrix)
#cluster_labels = clusterer.predict(reconstructedXmatrix)
gmm = mixture.GaussianMixture(n_components=5, covariance_type='full',
                              max_iter=500).fit(reconstructedXmatrix)


In [128]:
labels = gmm.predict(reconstructedXmatrix)

In [129]:
len(LabelVector)

125973

In [54]:
np.unique(labels)
len(labels)
np.unique(LabelVector)
encodedLabelVector = LabelVector.copy()
for i in LabelVector:
    if encodedLabelVector == 'dos':
        
    

array(['dos', 'normal', 'probe', 'r2l', 'u2r'], dtype=object)

In [ ]:
zippedLabel = zip(labels,LabelVector)

In [130]:
conMatrix = pd.crosstab(labels,LabelVector)

In [132]:
print(conMatrix)

col_0    dos  normal  probe  r2l  u2r
row_0                                
0       2592   45041    326   12    1
1       3741    2762    328  424   38
2      31662       0      0    0    0
3        902   11051   4678  519   11
4       7030    8489   6324   40    2


# part4

In [ ]:
from sklearn.cluster import AgglomerativeClustering
clustering = AgglomerativeClustering(n_clusters=5,affinity='euclidean', linkage='single',memory=None,compute_full_tree = 'false') .fit(reconstructedXmatrix[0:60000,:])
clustering 
#[0:30000,:]compute_full_tree : false
#AgglomerativeClustering(n_clusters=10,
# affinity=‘cosine’, linkage=‘complete’)
#AgglomerativeClustering(affinity='euclidean', compute_full_tree='auto',
 #           connectivity=None, linkage='ward', memory=None, n_clusters=2,
  #          pooling_func='deprecated')
#clustering.labels_
#array([1, 1, 1, 0, 0, 0])

In [17]:
labelsForAgClus = clustering.labels_

In [22]:
conMatrix = pd.crosstab(labelsForAgClus,LabelVector[0:30000])

In [23]:
print(conMatrix)

col_0   dos  normal  probe  r2l  u2r
row_0                               
0      2749   15958   2656  257   14
1      8244      34     88    0    0
